x = float(input('nhập hoành độ x:'))
y = float ( input('nhập tung độ y :'))
z = float(input('nhập cao độ z :'))
Oxy = (x, y ,-z)
Oxz = (x ,-y,z)
Oyz = (-x, y ,z)
print(f"điểm đối xứng qua mặt phẳng Oxy:{Oxy}")
print(f"điểm đối xứng qua mặt phẳng Oxz: {Oxz}")
print(f"điểm đối xứng qua mặt phẳng Oyz; {Oyz}")
