ma_sv = int(input("Nhap ma so sinh vien: "))
ho_ten = input("Nhap ho ten sinh vien: ")
que_quan = input("Nhap que quan sinh vien: ")
nam_sinh = input("Nhap nam sinh: ")
diem_tb = float(input("Nhap diem trung binh cac nam hoc: "))
print("Ma so sinh vien: ", ma_sv)
print("Ho ten sinh vien: ", ho_ten)
print("Que quan sinh vien: ", que_quan)
print("Nam sinh: ", nam_sinh)
print("Diem trung binh cac nam hoc: ", diem_tb)