#cau1:
ma_sv = input("Nhập mã số sinh viên: ")
ho_ten = input("Nhập họ tên: ")
que_quan = input("Nhập quê quán: ")
nam_sinh = int(input("Nhập năm sinh: "))
diem_tb = float(input("Nhập điểm trung bình: "))
print("\nThông tin sinh viên:")
print("Mã số sinh viên:", ma_sv)
print("Họ tên:", ho_ten)
print("Quê quán:", que_quan)
print("Năm sinh:", nam_sinh)
print("Điểm trung bình:", diem_tb)