x = float(input("Nhập hoành độ x:"))
y = float (input("Nhập tung độ y :"))
z = float(input("Nhập cao độ z :"))
Oxy = (x, y ,-z)
Oxz = (x ,-y,z)
Oyz = (-x, y ,z)
print(f"Điểm đối xứng qua mặt phẳng Oxy:{Oxy}")
print(f"Điểm đối xứng qua mặt phẳng Oxz: {Oxz}")
print(f"Điểm đối xứng qua mặt phẳng Oyz; {Oyz}")