a = float(input("Nhập hệ số a: "))
b = float(input("Nhập hệ số b: "))
c = float(input("Nhập hệ số c: "))
dinh_x = -b / (2 * a)
dinh_y= (4 * a * c - b**2) / (4 * a)
dinh_x = round(dinh_x, 2)
dinh_y = round(dinh_y, 2)
print(f"Tọa độ đỉnh của parabol: ({dinh_x}, {dinh_y})")