a = float(input("Nhập a: "))
b = float(input("Nhập b: "))
c = float(input("Nhập c: "))
x = -b / (2 * a) 
y = (4 * a * c - b ** 2) / (4 * a) 
print(f"Đỉnh của phương trình bậc 2 là: ({round(x, 2)}, {round(y, 2)})")