ma_sv=input("nhập vào mã sinh viên: ")
ho_ten=input("nhập họ tên: ")
que_quan=input("nhập quê quán: ")
nam_sinh=int(input("nhập năm sinh "))
diem_tb=float(input("nhập điểm trung bình: "))
print("Thông tin của sinh viên:")
print("mã sinh viên: ",ma_sv)
print("họ tên sinh viên: ",ho_ten)
print("quê quán: ",que_quan)
print("năm sinh: ",nam_sinh)
print("điểm trung bình: ",diem_tb)
