x = float(input("Nhập tọa độ x trong không gian: "))
y = float(input("Nhập tọa độ y trong không gian: "))
z = float(input("Nhập tọa độ z trong không gian: "))
oxy = (x, y, -z)
oyz = (-x, y, z)
oxz = (x, -y, z)
print(f"Tọa độ của điểm đối xứng qua mặt phẳng Oxy: {oxy}")
print(f"Tọa độ của điểm đối xứng qua mặt phẳng Oxz: {oxz}")
print(f"Tọa độ của điểm đối xứng qua mặt phẳng Oyz: {oyz}")